[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

# blocking shield
# borrowed from Cryptid (specifically https://github.com/MathIsFun0/Cryptid/blob/2a416baf61d63c48babc1ad581cf9df3e4f6dea2/lovely/blind.toml#L6C1-L21C20 )
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "func = (function()  update_hand_text({delay = 0, immediate = true}, {mult = 0, chips = 0, chip_total = math.floor(hand_chips*mult), level = '', handname = ''});play_sound('button', 0.9, 0.6);return true end)"
position = "at"
payload = "func = (function()  update_hand_text({delay = 0, immediate = true}, {mult = 0, chips = 0, chip_total = (#find_joker(\"j_bs_rc_shield\") > 0) and math.max(math.floor(hand_chips*mult), G.GAME.blind.chips*0.1) or math.floor(hand_chips*mult), level = '', handname = ''});play_sound('button', 0.9, 0.6);return true end)"
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "ease_to = G.GAME.chips + math.floor(hand_chips*mult),"
position = "at"
payload = "ease_to = G.GAME.chips + ((#find_joker(\"j_bs_rc_shield\") > 0) and math.max(math.floor(hand_chips*mult), G.GAME.blind.chips*0.1) or math.floor(hand_chips*mult)),"
match_indent = true